import { asset } from '../utils/asset.js'

export const zhihu = {
  id: 'zhihu',
  title: '知乎直播升级 - 2021',
  cover: {
    backgroundImage: `url(${asset('/src/assets/project/zhihu/zhihu.png')})`,
  },
  path: '/home/project/ZHIHU',
  images: [
    asset('/src/assets/project/zhihu/zhihu.png'),
    asset('/src/assets/project/zhihu/zhihu2.png'),
    asset('/src/assets/project/zhihu/zhihu3.png'),
    asset('/src/assets/project/zhihu/zhihu4.png'),
    asset('/src/assets/project/zhihu/zhihu5.png'),
    asset('/src/assets/project/zhihu/zhihu6.png'),
    asset('/src/assets/project/zhihu/zhihu7.png'),
    asset('/src/assets/project/zhihu/zhihu8.png'),
    asset('/src/assets/project/zhihu/zhihu9.png'),
    asset('/src/assets/project/zhihu/zhihu10.png'),
    asset('/src/assets/project/zhihu/zhihu11.png'),
    asset('/src/assets/project/zhihu/zhihu12.png'),
    asset('/src/assets/project/zhihu/zhihu13.png'),
    asset('/src/assets/project/zhihu/zhihu14.png'),
    asset('/src/assets/project/zhihu/zhihu15.png'),
    asset('/src/assets/project/zhihu/zhihu16.png'),
    asset('/src/assets/project/zhihu/zhihu17.png'),
    asset('/src/assets/project/zhihu/zhihu18.png'),
    asset('/src/assets/project/zhihu/zhihu19.png'),
    asset('/src/assets/project/zhihu/zhihu20.png'),
    asset('/src/assets/project/zhihu/zhihu21.png'),
    asset('/src/assets/project/zhihu/zhihu22.png'),
    asset('/src/assets/project/zhihu/zhihu23.png'),
    asset('/src/assets/project/zhihu/zhihu24.png'),
    asset('/src/assets/project/zhihu/zhihu25.png'),
    asset('/src/assets/project/zhihu/zhihu26.png'),
    asset('/src/assets/project/zhihu/zhihu27.png'),
    asset('/src/assets/project/zhihu/zhihu28.png'),
  ],
}
